feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 4000
        read-timeout: 5000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # must be greater than connect-timeout + read-timeout
            timeoutInMilliseconds: 10000

myfeignclient:
  ribbon:
    listOfServers: http://localhost:8085

logging:
  level:
    demo:
      nature:
        springbootsignatureclient:
          feign:
            MyFeignClient: debug






