feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

myfeignclient:
  ribbon:
    listOfServers: http://localhost:8085

logging:
  level:
    demo:
      nature:
        springbootsignatureclient:
          feign:
            MyFeignClient: debug




